apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chri5p-chri5p-poi-map-app-dev
  annotations:
    argocd/app-name: chri5p-chri5p-poi-map-app-dev
    backstage.io/kubernetes-id: chri5p-chri5p-poi-map-app-dev
    backstage.io/kubernetes-namespace: chri5p
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=chri5p-chri5p-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/chri5p-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/chri5p/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/chri5p/deployments/chri5p-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/chri5p-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://chri5p-poi-map-app-chri5p.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/chri5p"
  system: workshop-system-chri5p
  consumesApis:
    - gateway-api-chri5p
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-chri5p
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/chri5p"
